FROM public.ecr.aws/docker/library/node:10-alpine

WORKDIR /usr/src/app

COPY package*.json ./

RUN npm ci

COPY .env .env

COPY . .

# RUN npm run migrate:latest

EXPOSE 80

CMD ["npm", "run", "start:prod && npm run migrate:latest"]


# CMD ["sh", "-c", "cloud_sql_proxy -instances=<INSTANCE_CONNECTION_NAME>=tcp:5432 & npm run migrate:latest && npm run start:prod"]
