FROM public.ecr.aws/docker/library/node:10-alpine

WORKDIR /usr/src/app

COPY package*.json ./

RUN npm ci

COPY .env .env

COPY . .

RUN npm run migrate:latest

EXPOSE 80

CMD ["sh", "-c", "npm run migrate:latest && npm start:prod"]
